export const SAVE_USER_TOKEN = "SAVE_USER_TOKEN";
export const DELETE_USER_TOKEN = "DELETE_USER_TOKEN";

export const SAVE_USER_PROFILE = "SAVE_USER_PROFILE";
export const DELETE_USER_PROFILE = "DELETE_USER_PROFILE";

export const SAVE_USER_DATABASE = "SAVE_USER_DATABASE";
export const DELETE_USER_DATABASE = "DELETE_USER_DATABASE";

export const SAVE_ALL = "SAVE_ALL";
export const DELETE_ALL = "DELETE_ALL";

export type ACTION_TYPE =
  | "SAVE_USER_TOKEN"
  | "DELETE_USER_TOKEN"
  | "SAVE_USER_PROFILE"
  | "DELETE_USER_PROFILE"
  | "SAVE_USER_DATABASE"
  | "DELETE_USER_DATABASE"
  | "SAVE_ALL"
  | "DELETE_ALL";
